version: '3.8'

services:
  nextapp:
    build: .  # Build from the current directory (where the Dockerfile is)
    ports:
      - "3000:3000"
    volumes:
      - photo-volume:/storage/photos
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db

volumes:
  photo-volume:
  mongo-volume: